source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.3"
gem "pg"
gem "puma"
gem "bootsnap", require: false
gem "rack-cors"

# Shopify
gem "shopify_api"

# HTTP
gem "faraday"

# Security
gem "bcrypt"

group :development, :test do
  gem "dotenv-rails"
end
